stages:
  - build
  - quality
  - test

# Build phase.
# Installs necessary dependencies and save in node_modules.
build_next:
  stage: build
  image: node:latest
  cache:
    paths:
      - /client/beatson-app/node_modules
  before_script:
    - cd client/beatson-app
  script:
    - echo "building next..."
    - npm install
    - npm run build


# Quality assurance phase.
# Uses node modules previously installed in build_next and run linting.
quality_next_lint:
  stage: quality
  image: node:latest
  allow_failure: false
  cache:
    paths:
      - /client/beatson-app/node_modules
  before_script:
    - cd client/beatson-app
    - npm install
  script:
    - npm run lint

# Uses pylint on all python files.
quality_flask_neo4j_lint:
  image: python:latest
  stage: quality
  allow_failure: false
  before_script:
    - cd server
    - python -m venv .venv
    - source .venv/bin/activate
  script:
    - pip install -r requirements.txt
    - pip install .
    - pylint --output-format=parseable server

# Test phase.
# Tests using jest ran, node_modules form build phase used.
test_frontend:
  stage: test
  image: node
  cache:
    paths:
      - /client/beatson-app/node_modules
  before_script:
    - cd client/beatson-app
  script:
    - npm install
    - npm test

before_script:
    - echo DB_PASSWORD is $DB_PASSWORD